version: "3"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - mongodb
  mongodb:
    image: "mongo:latest"
    ports:
      - "27017:27017"
